export const CATALOG_COURSES = [
  {
    id: 'fullstack-web',
    title: 'Fullstack Web Development Professional Certificate',
    provider: 'LearnFlow',
    instructor: 'Sarah Chen',
    instructorTitle: 'Senior Software Engineer, Ex-Google',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/ysEN5RaKOlA',
    rating: 4.8,
    reviewCount: 12400,
    students: 84200,
    duration: '6 months',
    hoursPerWeek: '10 hrs/week',
    level: 'Beginner',
    price: '$49.99',
    originalPrice: '$199.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Master HTML, CSS, JavaScript, React, Node.js and databases to become a job-ready fullstack developer.',
    description: 'This professional certificate program takes you from zero to a job-ready fullstack developer. You will build real-world projects, learn modern frameworks, and graduate with a portfolio that impresses employers.',
    benefits: [
      'Build 10+ real-world projects for your portfolio',
      'Learn the most in-demand web technologies',
      'Get a shareable certificate recognized by top employers',
      'Access to career support and job placement assistance',
      'Lifetime access to course materials and updates',
      'Join a community of 80,000+ learners worldwide',
    ],
    skills: ['HTML & CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB', 'REST APIs', 'Git & GitHub', 'Deployment'],
    curriculum: [
      { module: 'Module 1', title: 'HTML & CSS Fundamentals', lessons: 12, duration: '2 weeks', description: 'Build the visual structure of web pages with semantic HTML and modern CSS.' },
      { module: 'Module 2', title: 'JavaScript Essentials', lessons: 18, duration: '3 weeks', description: 'Master core JS concepts: variables, functions, DOM manipulation, and async programming.' },
      { module: 'Module 3', title: 'React & Frontend Development', lessons: 20, duration: '4 weeks', description: 'Build dynamic UIs with React, hooks, state management, and component architecture.' },
      { module: 'Module 4', title: 'Node.js & Backend APIs', lessons: 16, duration: '3 weeks', description: 'Create RESTful APIs with Express, handle authentication, and connect to databases.' },
      { module: 'Module 5', title: 'Databases & Data Modeling', lessons: 10, duration: '2 weeks', description: 'Work with MongoDB and SQL databases, design schemas, and write efficient queries.' },
      { module: 'Module 6', title: 'Capstone Project & Deployment', lessons: 8, duration: '2 weeks', description: 'Build and deploy a full-stack application to production using cloud platforms.' },
    ],
    reviews: [
      { name: 'Jordan M.', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=60&h=60&fit=crop', rating: 5, comment: 'This course completely changed my career. I landed a junior dev role 2 months after finishing!', date: 'Jan 2026' },
      { name: 'Priya S.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop', rating: 5, comment: 'Sarah explains everything so clearly. The projects are challenging but very rewarding.', date: 'Feb 2026' },
      { name: 'Carlos R.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop', rating: 4, comment: 'Great content overall. The Node.js section could use a bit more depth but everything else is excellent.', date: 'Mar 2026' },
    ],
  },
  {
    id: 'google-data-analytics',
    title: 'Google Data Analytics Professional Certificate',
    provider: 'Google',
    instructor: 'Google Career Certificates',
    instructorTitle: 'Official Google Training Program',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop',
    category: 'Professional Certificates',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bbda38a88ad8?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/EN7h2t_tBSY',
    rating: 4.7,
    reviewCount: 98000,
    students: 2100000,
    duration: '6 months',
    hoursPerWeek: '10 hrs/week',
    level: 'Beginner',
    price: '$39.99',
    originalPrice: '$149.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Get job-ready for an entry-level data analyst role. Learn from Google employees whose work in data informs thousands of business decisions.',
    description: 'Prepare for a new career in the high-growth field of data analytics, no experience or degree required. Get professional training designed by Google and have the opportunity to connect with top employers.',
    benefits: [
      'Earn a credential from Google',
      'Prepare for the CompTIA Data+ exam',
      'Learn job-ready skills in under 6 months',
      'Access to 150+ hiring partners including Google',
      'Hands-on projects with real datasets',
      'Career support resources and interview prep',
    ],
    skills: ['Data Cleaning', 'Data Analysis', 'SQL', 'Tableau', 'R Programming', 'Data Visualization', 'Spreadsheets', 'Problem Solving'],
    curriculum: [
      { module: 'Course 1', title: 'Foundations: Data, Data, Everywhere', lessons: 10, duration: '3 weeks', description: 'Understand the data ecosystem and the role of a data analyst.' },
      { module: 'Course 2', title: 'Ask Questions to Make Data-Driven Decisions', lessons: 12, duration: '3 weeks', description: 'Learn how to ask effective questions and use structured thinking.' },
      { module: 'Course 3', title: 'Prepare Data for Exploration', lessons: 14, duration: '3 weeks', description: 'Understand data types, structures, and best practices for data integrity.' },
      { module: 'Course 4', title: 'Process Data from Dirty to Clean', lessons: 16, duration: '4 weeks', description: 'Clean and transform data using spreadsheets and SQL.' },
      { module: 'Course 5', title: 'Analyze Data to Answer Questions', lessons: 14, duration: '4 weeks', description: 'Organize and format data for analysis using SQL and spreadsheets.' },
      { module: 'Course 6', title: 'Share Data Through the Art of Visualization', lessons: 12, duration: '3 weeks', description: 'Create visualizations and dashboards with Tableau.' },
      { module: 'Course 7', title: 'Data Analysis with R Programming', lessons: 14, duration: '4 weeks', description: 'Use R for data analysis, visualization, and documentation.' },
      { module: 'Course 8', title: 'Capstone: Complete a Case Study', lessons: 6, duration: '2 weeks', description: 'Complete a case study to practice your data analytics skills.' },
    ],
    reviews: [
      { name: 'Amara T.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Got my first data analyst job 3 months after completing this. The Google name really opens doors.', date: 'Feb 2026' },
      { name: 'Wei L.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop', rating: 5, comment: 'Very comprehensive. The SQL and Tableau sections alone are worth the price.', date: 'Jan 2026' },
      { name: 'Sofia B.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Great for beginners. Some sections feel a bit slow but the overall quality is top notch.', date: 'Mar 2026' },
    ],
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning Specialization',
    provider: 'DeepLearning.AI',
    instructor: 'Andrew Ng',
    instructorTitle: 'Co-founder of Coursera, Adjunct Professor at Stanford',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    category: 'Courses & Specializations',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/vStJoetOxJg',
    rating: 4.9,
    reviewCount: 156000,
    students: 4500000,
    duration: '3 months',
    hoursPerWeek: '9 hrs/week',
    level: 'Intermediate',
    price: '$59.99',
    originalPrice: '$249.99',
    language: 'English',
    lastUpdated: 'January 2026',
    shortDescription: 'Build ML models with NumPy & scikit-learn, build & train neural networks with TensorFlow, apply best practices for ML development.',
    description: 'The Machine Learning Specialization is a foundational online program created in collaboration between DeepLearning.AI and Stanford Online. This beginner-friendly program will teach you the fundamentals of machine learning and how to use these techniques to build real-world AI applications.',
    benefits: [
      'Master the most in-demand ML skills',
      'Build and train neural networks with TensorFlow',
      'Apply ML to real-world problems',
      'Learn from Andrew Ng, a pioneer in AI',
      'Earn a certificate from DeepLearning.AI & Stanford',
      'Access to a global community of ML practitioners',
    ],
    skills: ['Supervised Learning', 'Unsupervised Learning', 'Neural Networks', 'TensorFlow', 'Python', 'NumPy', 'scikit-learn', 'Recommender Systems'],
    curriculum: [
      { module: 'Course 1', title: 'Supervised Machine Learning', lessons: 18, duration: '4 weeks', description: 'Build regression and classification models using Python and scikit-learn.' },
      { module: 'Course 2', title: 'Advanced Learning Algorithms', lessons: 20, duration: '4 weeks', description: 'Build and train neural networks, decision trees, and ensemble methods.' },
      { module: 'Course 3', title: 'Unsupervised Learning & Recommenders', lessons: 16, duration: '3 weeks', description: 'Implement clustering, anomaly detection, and recommender systems.' },
    ],
    reviews: [
      { name: 'Raj P.', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=60&h=60&fit=crop', rating: 5, comment: 'Andrew Ng is the GOAT of ML education. This course is the gold standard.', date: 'Mar 2026' },
      { name: 'Elena K.', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=60&h=60&fit=crop', rating: 5, comment: 'Incredibly well structured. I went from knowing nothing to building my own models.', date: 'Feb 2026' },
      { name: 'David O.', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=60&h=60&fit=crop', rating: 5, comment: 'Best investment I have made in my career. The math is explained intuitively.', date: 'Jan 2026' },
    ],
  },
  {
    id: 'digital-marketing',
    title: 'Advanced Digital Marketing Specialization',
    provider: 'LearnFlow',
    instructor: 'Marketing Pros Team',
    instructorTitle: 'Industry Marketing Experts',
    instructorAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop',
    category: 'Courses & Specializations',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/bixR-KIJKYM',
    rating: 4.6,
    reviewCount: 34000,
    students: 210000,
    duration: '4 months',
    hoursPerWeek: '8 hrs/week',
    level: 'Beginner',
    price: '$34.99',
    originalPrice: '$129.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Master SEO, social media, email marketing, Google Ads, and analytics to grow any business online.',
    description: 'This specialization covers all aspects of digital marketing from strategy to execution. You will learn how to drive traffic, convert leads, and measure results across every major digital channel.',
    benefits: [
      'Master all major digital marketing channels',
      'Build and execute real marketing campaigns',
      'Get Google Ads and Analytics certified',
      'Learn from active marketing professionals',
      'Build a portfolio of marketing case studies',
      'Career support and freelancing guidance',
    ],
    skills: ['SEO', 'Google Ads', 'Social Media Marketing', 'Email Marketing', 'Content Strategy', 'Google Analytics', 'Copywriting', 'A/B Testing'],
    curriculum: [
      { module: 'Module 1', title: 'Digital Marketing Foundations', lessons: 10, duration: '2 weeks', description: 'Understand the digital marketing landscape and build your strategy.' },
      { module: 'Module 2', title: 'SEO & Content Marketing', lessons: 14, duration: '3 weeks', description: 'Rank on Google with on-page SEO, keyword research, and content creation.' },
      { module: 'Module 3', title: 'Paid Advertising (Google & Meta)', lessons: 16, duration: '3 weeks', description: 'Run profitable ad campaigns on Google, Facebook, and Instagram.' },
      { module: 'Module 4', title: 'Social Media & Email Marketing', lessons: 12, duration: '3 weeks', description: 'Build audiences and nurture leads through social and email channels.' },
      { module: 'Module 5', title: 'Analytics & Optimization', lessons: 10, duration: '3 weeks', description: 'Measure performance, run A/B tests, and optimize for ROI.' },
    ],
    reviews: [
      { name: 'Fatima A.', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=60&h=60&fit=crop', rating: 5, comment: 'Grew my client\'s Instagram from 2k to 50k followers using what I learned here.', date: 'Feb 2026' },
      { name: 'Tom H.', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=60&h=60&fit=crop', rating: 4, comment: 'Very practical. The Google Ads section alone paid for the course many times over.', date: 'Jan 2026' },
    ],
  },
  {
    id: 'python-everybody',
    title: 'Python for Everybody Specialization',
    provider: 'University of Michigan',
    instructor: 'Dr. Charles Severance',
    instructorTitle: 'Clinical Professor, University of Michigan',
    instructorAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/8DvywoWv6fI',
    rating: 4.8,
    reviewCount: 245000,
    students: 5800000,
    duration: '8 months',
    hoursPerWeek: '4 hrs/week',
    level: 'Beginner',
    price: '$29.99',
    originalPrice: '$99.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Learn to program and analyze data with Python. Develop programs to gather, clean, analyze, and visualize data.',
    description: 'This specialization introduces fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language. In the Capstone Project, you will use the technologies learned throughout the Specialization to design and create your own applications for data retrieval, processing, and visualization.',
    benefits: [
      'No prior programming experience needed',
      'Learn Python from a world-class university',
      'Build real data-driven applications',
      'Earn a University of Michigan certificate',
      'Access to 5.8 million learner community',
      'Flexible schedule — learn at your own pace',
    ],
    skills: ['Python', 'Data Structures', 'Web Scraping', 'SQL', 'JSON & XML', 'Data Visualization', 'APIs', 'Database Design'],
    curriculum: [
      { module: 'Course 1', title: 'Programming for Everybody (Python)', lessons: 14, duration: '7 weeks', description: 'Learn the basics of programming computers using Python.' },
      { module: 'Course 2', title: 'Python Data Structures', lessons: 12, duration: '6 weeks', description: 'Explore the core data structures of Python: lists, dictionaries, and tuples.' },
      { module: 'Course 3', title: 'Using Python to Access Web Data', lessons: 12, duration: '6 weeks', description: 'Scrape, parse, and read web data using Python.' },
      { module: 'Course 4', title: 'Using Databases with Python', lessons: 10, duration: '5 weeks', description: 'Use SQLite to store and retrieve data in Python applications.' },
      { module: 'Course 5', title: 'Capstone: Retrieving, Processing & Visualizing Data', lessons: 8, duration: '4 weeks', description: 'Build a complete data application from scratch.' },
    ],
    reviews: [
      { name: 'Ngozi E.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Chuck is the best teacher I have ever had. Made Python feel easy and fun.', date: 'Mar 2026' },
      { name: 'Liam W.', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=60&h=60&fit=crop', rating: 5, comment: 'Started with zero coding knowledge. Now I write Python scripts for my job daily.', date: 'Feb 2026' },
      { name: 'Yuki T.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Excellent pacing for beginners. The database section is particularly well done.', date: 'Jan 2026' },
    ],
  },
  {
    id: 'google-cybersecurity',
    title: 'Google Cybersecurity Certificate',
    provider: 'Google',
    instructor: 'Google Career Certificates',
    instructorTitle: 'Official Google Training Program',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop',
    category: 'Professional Certificates',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/inWWhr5tnEA',
    rating: 4.7,
    reviewCount: 67000,
    students: 890000,
    duration: '6 months',
    hoursPerWeek: '7 hrs/week',
    level: 'Beginner',
    price: '$39.99',
    originalPrice: '$149.99',
    language: 'English',
    lastUpdated: 'January 2026',
    shortDescription: 'Prepare for a career in cybersecurity. Learn from Google employees whose work in security protects billions of users.',
    description: 'This certificate program prepares you for an entry-level job in cybersecurity in under 6 months. No prior experience needed. You will learn the foundations of cybersecurity, network security, Linux, SQL, Python, and more.',
    benefits: [
      'Earn a credential from Google',
      'Prepare for the CompTIA Security+ exam',
      'Learn job-ready skills in under 6 months',
      'Access to 150+ hiring partners',
      'Hands-on labs with real security tools',
      'Career support and interview preparation',
    ],
    skills: ['Network Security', 'Linux', 'SQL', 'Python', 'SIEM Tools', 'Intrusion Detection', 'Risk Management', 'Incident Response'],
    curriculum: [
      { module: 'Course 1', title: 'Foundations of Cybersecurity', lessons: 10, duration: '3 weeks', description: 'Explore the cybersecurity profession and the core skills required.' },
      { module: 'Course 2', title: 'Play It Safe: Manage Security Risks', lessons: 12, duration: '3 weeks', description: 'Identify how cybersecurity professionals use frameworks and controls.' },
      { module: 'Course 3', title: 'Connect and Protect: Networks and Network Security', lessons: 14, duration: '4 weeks', description: 'Understand network architecture and how to secure it.' },
      { module: 'Course 4', title: 'Tools of the Trade: Linux and SQL', lessons: 16, duration: '4 weeks', description: 'Use Linux command line and SQL to investigate security incidents.' },
      { module: 'Course 5', title: 'Assets, Threats, and Vulnerabilities', lessons: 14, duration: '4 weeks', description: 'Classify assets and identify threats and vulnerabilities.' },
      { module: 'Course 6', title: 'Sound the Alarm: Detection and Response', lessons: 12, duration: '3 weeks', description: 'Understand incident detection and response processes.' },
      { module: 'Course 7', title: 'Automate Cybersecurity Tasks with Python', lessons: 14, duration: '4 weeks', description: 'Use Python to automate common cybersecurity tasks.' },
      { module: 'Course 8', title: 'Put It to Work: Prepare for Cybersecurity Jobs', lessons: 8, duration: '2 weeks', description: 'Prepare for your job search with resume and interview tips.' },
    ],
    reviews: [
      { name: 'Marcus J.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop', rating: 5, comment: 'Passed my CompTIA Security+ on the first try after this course. Highly recommend.', date: 'Feb 2026' },
      { name: 'Aisha M.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Career changer here. Got a SOC analyst role 2 months after finishing. Life changing.', date: 'Mar 2026' },
    ],
  },

  // ── 10 SKILLS COURSES ──────────────────────────────────────────────────────

  {
    id: 'accounting',
    title: 'Accounting',
    provider: 'LearnFlow',
    instructor: 'Dr. Linda Marsh (CPA)',
    instructorTitle: 'Certified Public Accountant, 20+ years in practice',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/yYX4bvQSqbo',
    rating: 4.7,
    reviewCount: 18400,
    students: 142000,
    duration: '4 months',
    hoursPerWeek: '8 hrs/week',
    level: 'Beginner',
    price: '$34.99',
    originalPrice: '$129.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Master the fundamentals of accounting, financial statements, bookkeeping, and tax principles with a practicing CPA.',
    description: 'This course gives you a solid foundation in accounting principles used by businesses worldwide. From debits and credits to financial reporting and tax basics, Dr. Linda Marsh walks you through everything step by step.',
    benefits: [
      'Understand financial statements inside and out',
      'Learn bookkeeping from a practicing CPA',
      'Prepare for the CPA or bookkeeping certification',
      'Apply accounting to real business scenarios',
      'Build skills valued in every industry',
      'Lifetime access and certificate included',
    ],
    skills: ['Bookkeeping', 'Financial Statements', 'Debits & Credits', 'Tax Basics', 'Payroll', 'QuickBooks', 'Budgeting', 'Auditing Fundamentals'],
    curriculum: [
      { module: 'Module 1', title: 'Accounting Fundamentals', lessons: 10, duration: '2 weeks', description: 'Understand the accounting equation, debits, credits, and the chart of accounts.' },
      { module: 'Module 2', title: 'Bookkeeping & Journal Entries', lessons: 12, duration: '3 weeks', description: 'Record transactions, maintain ledgers, and prepare trial balances.' },
      { module: 'Module 3', title: 'Financial Statements', lessons: 14, duration: '3 weeks', description: 'Prepare income statements, balance sheets, and cash flow statements.' },
      { module: 'Module 4', title: 'Payroll & Accounts Management', lessons: 10, duration: '2 weeks', description: 'Process payroll, manage accounts payable and receivable.' },
      { module: 'Module 5', title: 'Tax Principles & Compliance', lessons: 12, duration: '2 weeks', description: 'Understand business tax obligations, deductions, and filing basics.' },
      { module: 'Module 6', title: 'Capstone: Full Business Accounting Cycle', lessons: 8, duration: '4 weeks', description: 'Complete a full accounting cycle for a simulated business from start to finish.' },
    ],
    reviews: [
      { name: 'Blessing O.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Marsh makes accounting so approachable. I passed my bookkeeping exam on the first try!', date: 'Feb 2026' },
      { name: 'Kevin T.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop', rating: 5, comment: 'Best accounting course online. The real-world examples make everything click.', date: 'Jan 2026' },
      { name: 'Sandra L.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Very thorough. The tax module could go a bit deeper but overall excellent quality.', date: 'Mar 2026' },
    ],
  },

  {
    id: 'artificial-intelligence',
    title: 'Artificial Intelligence (AI)',
    provider: 'LearnFlow',
    instructor: 'Dr. Anika Patel (Ex-DeepMind)',
    instructorTitle: 'AI Research Scientist, Ex-DeepMind',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/ad79nYk2keg',
    rating: 4.9,
    reviewCount: 52000,
    students: 380000,
    duration: '5 months',
    hoursPerWeek: '10 hrs/week',
    level: 'Intermediate',
    price: '$49.99',
    originalPrice: '$199.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Learn AI fundamentals, machine learning, neural networks, and real-world AI applications from an Ex-DeepMind researcher.',
    description: 'Dr. Anika Patel brings her DeepMind experience to this comprehensive AI course. You will go from AI fundamentals to building and deploying intelligent systems, covering the theory and practice that top AI labs use every day.',
    benefits: [
      'Learn from an Ex-DeepMind AI researcher',
      'Build and deploy real AI models',
      'Understand the math behind AI intuitively',
      'Cover NLP, computer vision, and reinforcement learning',
      'Earn a certificate recognized by top tech companies',
      'Access to exclusive AI project community',
    ],
    skills: ['Machine Learning', 'Neural Networks', 'NLP', 'Computer Vision', 'Python', 'TensorFlow', 'PyTorch', 'Reinforcement Learning'],
    curriculum: [
      { module: 'Module 1', title: 'AI Foundations & History', lessons: 10, duration: '2 weeks', description: 'Understand what AI is, its history, and the landscape of modern AI systems.' },
      { module: 'Module 2', title: 'Machine Learning Core', lessons: 16, duration: '4 weeks', description: 'Build supervised and unsupervised learning models from scratch.' },
      { module: 'Module 3', title: 'Deep Learning & Neural Networks', lessons: 18, duration: '4 weeks', description: 'Design and train deep neural networks with TensorFlow and PyTorch.' },
      { module: 'Module 4', title: 'Natural Language Processing', lessons: 14, duration: '3 weeks', description: 'Build text classifiers, chatbots, and language models.' },
      { module: 'Module 5', title: 'Computer Vision', lessons: 12, duration: '3 weeks', description: 'Build image recognition and object detection systems.' },
      { module: 'Module 6', title: 'AI Deployment & Ethics', lessons: 10, duration: '4 weeks', description: 'Deploy AI models to production and understand responsible AI principles.' },
    ],
    reviews: [
      { name: 'Tariq B.', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Patel explains complex AI concepts better than any textbook I have read. Incredible course.', date: 'Mar 2026' },
      { name: 'Mei L.', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=60&h=60&fit=crop', rating: 5, comment: 'The DeepMind insights are priceless. You can tell this is taught by someone who has done it for real.', date: 'Feb 2026' },
      { name: 'Omar S.', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=60&h=60&fit=crop', rating: 5, comment: 'Best AI course available anywhere. Period.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'cybersecurity-skill',
    title: 'Cybersecurity',
    provider: 'LearnFlow',
    instructor: 'Marcus Webb (Ex-NSA)',
    instructorTitle: 'Cybersecurity Expert, Ex-NSA Analyst',
    instructorAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/inWWhr5tnEA',
    rating: 4.8,
    reviewCount: 41000,
    students: 295000,
    duration: '5 months',
    hoursPerWeek: '9 hrs/week',
    level: 'Beginner',
    price: '$44.99',
    originalPrice: '$179.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Learn ethical hacking, network defense, and threat analysis from a former NSA cybersecurity analyst.',
    description: 'Marcus Webb spent years protecting national infrastructure at the NSA. Now he teaches you the exact skills used by elite security professionals — from penetration testing to incident response.',
    benefits: [
      'Learn from a former NSA cybersecurity analyst',
      'Master ethical hacking and penetration testing',
      'Prepare for CompTIA Security+ and CEH certifications',
      'Hands-on labs with real security tools',
      'Understand how attackers think and operate',
      'Career support for security analyst roles',
    ],
    skills: ['Ethical Hacking', 'Network Defense', 'Penetration Testing', 'SIEM', 'Threat Analysis', 'Linux Security', 'Cryptography', 'Incident Response'],
    curriculum: [
      { module: 'Module 1', title: 'Cybersecurity Fundamentals', lessons: 10, duration: '2 weeks', description: 'Understand the threat landscape, attack vectors, and defense strategies.' },
      { module: 'Module 2', title: 'Network Security & Architecture', lessons: 14, duration: '3 weeks', description: 'Secure networks, configure firewalls, and monitor traffic.' },
      { module: 'Module 3', title: 'Ethical Hacking & Penetration Testing', lessons: 18, duration: '4 weeks', description: 'Learn to think like an attacker and find vulnerabilities before they do.' },
      { module: 'Module 4', title: 'Cryptography & Identity Management', lessons: 12, duration: '3 weeks', description: 'Implement encryption, PKI, and access control systems.' },
      { module: 'Module 5', title: 'Threat Detection & SIEM', lessons: 14, duration: '3 weeks', description: 'Use SIEM tools to detect, analyze, and respond to threats in real time.' },
      { module: 'Module 6', title: 'Incident Response & Capstone', lessons: 10, duration: '5 weeks', description: 'Lead a full incident response exercise on a simulated breach scenario.' },
    ],
    reviews: [
      { name: 'James K.', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=60&h=60&fit=crop', rating: 5, comment: 'Marcus brings real NSA-level knowledge. The penetration testing labs are incredibly realistic.', date: 'Feb 2026' },
      { name: 'Nadia F.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop', rating: 5, comment: 'Passed Security+ after this course. The way Marcus explains attack techniques is eye-opening.', date: 'Mar 2026' },
      { name: 'Dayo A.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop', rating: 4, comment: 'Excellent course. Some labs require a decent PC to run the VMs but the content is top tier.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'data-analytics-skill',
    title: 'Data Analytics',
    provider: 'LearnFlow',
    instructor: 'Dr. Yemi Adeyemi (Ex-Amazon)',
    instructorTitle: 'Senior Data Scientist, Ex-Amazon',
    instructorAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bbda38a88ad8?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/EN7h2t_tBSY',
    rating: 4.8,
    reviewCount: 37500,
    students: 260000,
    duration: '4 months',
    hoursPerWeek: '9 hrs/week',
    level: 'Beginner',
    price: '$39.99',
    originalPrice: '$159.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Go from raw data to actionable insights using SQL, Python, Tableau, and the analytical frameworks used at Amazon.',
    description: 'Dr. Yemi Adeyemi brings Amazon-scale data thinking to this practical analytics course. You will learn to collect, clean, analyze, and visualize data to drive real business decisions.',
    benefits: [
      'Learn analytics frameworks used at Amazon',
      'Master SQL, Python, and Tableau',
      'Build a portfolio of data analysis projects',
      'Understand A/B testing and statistical analysis',
      'Earn a job-ready data analytics certificate',
      'Access to exclusive datasets and case studies',
    ],
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistical Analysis', 'A/B Testing', 'Data Cleaning', 'Dashboard Design'],
    curriculum: [
      { module: 'Module 1', title: 'Data Analytics Foundations', lessons: 10, duration: '2 weeks', description: 'Understand the data analytics workflow and key tools used in industry.' },
      { module: 'Module 2', title: 'SQL for Data Analysis', lessons: 16, duration: '3 weeks', description: 'Write complex SQL queries to extract and transform data from databases.' },
      { module: 'Module 3', title: 'Python for Analytics', lessons: 18, duration: '4 weeks', description: 'Use pandas, NumPy, and matplotlib to analyze and visualize data.' },
      { module: 'Module 4', title: 'Statistics & A/B Testing', lessons: 12, duration: '3 weeks', description: 'Apply statistical thinking to validate hypotheses and run experiments.' },
      { module: 'Module 5', title: 'Data Visualization with Tableau', lessons: 12, duration: '3 weeks', description: 'Build interactive dashboards and compelling data stories.' },
      { module: 'Module 6', title: 'Capstone: End-to-End Analytics Project', lessons: 8, duration: '5 weeks', description: 'Analyze a real dataset and present findings to a simulated stakeholder panel.' },
    ],
    reviews: [
      { name: 'Chioma E.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Yemi teaches analytics the way it is actually done at top companies. Invaluable.', date: 'Mar 2026' },
      { name: 'Paul M.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop', rating: 5, comment: 'The SQL and Python sections are incredibly practical. Got a data analyst role within 2 months.', date: 'Feb 2026' },
      { name: 'Hana K.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Great course. The Tableau section is the best I have seen anywhere online.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'digital-marketing-skill',
    title: 'Digital Marketing',
    provider: 'LearnFlow',
    instructor: 'Sofia Reyes (Ex-HubSpot)',
    instructorTitle: 'Growth Marketing Lead, Ex-HubSpot',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/bixR-KIJKYM',
    rating: 4.7,
    reviewCount: 29000,
    students: 198000,
    duration: '3 months',
    hoursPerWeek: '8 hrs/week',
    level: 'Beginner',
    price: '$29.99',
    originalPrice: '$119.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Learn SEO, paid ads, email marketing, and social media strategy from a former HubSpot growth lead.',
    description: 'Sofia Reyes scaled multiple brands at HubSpot using the exact strategies she teaches in this course. You will learn to build and execute digital marketing campaigns that actually drive results.',
    benefits: [
      'Learn from a former HubSpot growth marketing lead',
      'Build real campaigns across all major channels',
      'Get HubSpot Marketing certified',
      'Master SEO, paid ads, email, and social media',
      'Build a portfolio of marketing case studies',
      'Freelancing and agency career guidance included',
    ],
    skills: ['SEO', 'Google Ads', 'Meta Ads', 'Email Marketing', 'Content Strategy', 'HubSpot CRM', 'Analytics', 'Conversion Optimization'],
    curriculum: [
      { module: 'Module 1', title: 'Digital Marketing Strategy', lessons: 10, duration: '2 weeks', description: 'Build a full-funnel digital marketing strategy from scratch.' },
      { module: 'Module 2', title: 'SEO & Content Marketing', lessons: 14, duration: '3 weeks', description: 'Rank on Google with keyword research, on-page SEO, and content creation.' },
      { module: 'Module 3', title: 'Paid Advertising (Google & Meta)', lessons: 14, duration: '3 weeks', description: 'Run profitable ad campaigns on Google, Facebook, and Instagram.' },
      { module: 'Module 4', title: 'Email Marketing & Automation', lessons: 10, duration: '2 weeks', description: 'Build email sequences, segment audiences, and automate campaigns.' },
      { module: 'Module 5', title: 'Social Media Marketing', lessons: 10, duration: '2 weeks', description: 'Grow organic audiences and manage brand presence across platforms.' },
      { module: 'Module 6', title: 'Analytics & Campaign Optimization', lessons: 8, duration: '4 weeks', description: 'Measure ROI, run A/B tests, and optimize campaigns for maximum performance.' },
    ],
    reviews: [
      { name: 'Amina D.', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=60&h=60&fit=crop', rating: 5, comment: 'Sofia teaches marketing the way it is actually done at top companies. Landed my first marketing job!', date: 'Feb 2026' },
      { name: 'Ryan C.', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=60&h=60&fit=crop', rating: 5, comment: 'The paid ads section alone is worth 10x the price. My ROAS went from 1.2x to 4.8x.', date: 'Mar 2026' },
      { name: 'Zara M.', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=60&h=60&fit=crop', rating: 4, comment: 'Excellent practical content. Would love more depth on TikTok ads but everything else is great.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'human-resources',
    title: 'Human Resources (HR)',
    provider: 'LearnFlow',
    instructor: 'Dr. Keisha Thompson (SHRM-SCP)',
    instructorTitle: 'SHRM Senior Certified Professional, 15+ years in HR',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/4CROQR4LFxk',
    rating: 4.6,
    reviewCount: 21000,
    students: 155000,
    duration: '4 months',
    hoursPerWeek: '7 hrs/week',
    level: 'Beginner',
    price: '$34.99',
    originalPrice: '$129.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Master HR fundamentals, talent acquisition, employee relations, and HR strategy with a SHRM-SCP certified professional.',
    description: 'Dr. Keisha Thompson brings 15 years of HR leadership to this comprehensive course. From recruiting and onboarding to performance management and labor law, you will be ready for a career in HR.',
    benefits: [
      'Learn from a SHRM Senior Certified Professional',
      'Prepare for the SHRM-CP or PHR certification',
      'Master the full employee lifecycle',
      'Understand employment law and compliance',
      'Build HR policies and procedures from scratch',
      'Career support for HR generalist and specialist roles',
    ],
    skills: ['Talent Acquisition', 'Onboarding', 'Performance Management', 'Employee Relations', 'HR Analytics', 'Labor Law', 'Compensation & Benefits', 'HRIS Systems'],
    curriculum: [
      { module: 'Module 1', title: 'HR Foundations & Strategy', lessons: 10, duration: '2 weeks', description: 'Understand the role of HR in organizations and how to align HR with business strategy.' },
      { module: 'Module 2', title: 'Talent Acquisition & Recruiting', lessons: 14, duration: '3 weeks', description: 'Source, screen, and hire top talent using modern recruiting techniques.' },
      { module: 'Module 3', title: 'Onboarding & Employee Development', lessons: 12, duration: '3 weeks', description: 'Design onboarding programs and create learning & development initiatives.' },
      { module: 'Module 4', title: 'Performance Management & Compensation', lessons: 12, duration: '3 weeks', description: 'Build performance review systems and design competitive compensation structures.' },
      { module: 'Module 5', title: 'Employee Relations & Labor Law', lessons: 14, duration: '3 weeks', description: 'Handle workplace conflicts, understand employment law, and ensure compliance.' },
      { module: 'Module 6', title: 'HR Analytics & Capstone', lessons: 8, duration: '4 weeks', description: 'Use data to drive HR decisions and complete a full HR strategy project.' },
    ],
    reviews: [
      { name: 'Tolu A.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Thompson is an amazing instructor. Passed my SHRM-CP exam after this course!', date: 'Mar 2026' },
      { name: 'Grace N.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 5, comment: 'The labor law section is incredibly thorough. This course is worth every penny.', date: 'Feb 2026' },
      { name: 'Ben O.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop', rating: 4, comment: 'Great course for HR beginners. The real-world case studies make the content very relatable.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'microsoft-excel',
    title: 'Microsoft Excel',
    provider: 'LearnFlow',
    instructor: 'Chris Dutton (Microsoft MVP)',
    instructorTitle: 'Microsoft MVP, Excel & Business Intelligence Expert',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/Vl0H-qTclOg',
    rating: 4.8,
    reviewCount: 88000,
    students: 720000,
    duration: '2 months',
    hoursPerWeek: '6 hrs/week',
    level: 'Beginner',
    price: '$24.99',
    originalPrice: '$89.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Go from Excel beginner to power user. Master formulas, pivot tables, dashboards, and Power Query with a Microsoft MVP.',
    description: 'Chris Dutton is one of the most recognized Excel educators in the world. This course takes you from the basics all the way to advanced data modeling, automation with macros, and building professional dashboards.',
    benefits: [
      'Learn from a Microsoft Most Valuable Professional',
      'Master 100+ Excel functions and formulas',
      'Build professional dashboards and reports',
      'Automate tasks with macros and VBA basics',
      'Prepare for the Microsoft Office Specialist exam',
      'Skills applicable to any industry or role',
    ],
    skills: ['Excel Formulas', 'Pivot Tables', 'VLOOKUP & XLOOKUP', 'Power Query', 'Charts & Dashboards', 'Conditional Formatting', 'Macros & VBA', 'Data Validation'],
    curriculum: [
      { module: 'Module 1', title: 'Excel Fundamentals', lessons: 12, duration: '1 week', description: 'Navigate Excel, enter data, and use basic formulas and functions.' },
      { module: 'Module 2', title: 'Core Formulas & Functions', lessons: 16, duration: '2 weeks', description: 'Master IF, VLOOKUP, XLOOKUP, INDEX/MATCH, and text functions.' },
      { module: 'Module 3', title: 'Data Analysis with Pivot Tables', lessons: 14, duration: '2 weeks', description: 'Summarize and analyze large datasets with pivot tables and pivot charts.' },
      { module: 'Module 4', title: 'Charts, Dashboards & Visualization', lessons: 12, duration: '2 weeks', description: 'Build dynamic charts and interactive dashboards for business reporting.' },
      { module: 'Module 5', title: 'Power Query & Data Modeling', lessons: 10, duration: '2 weeks', description: 'Import, transform, and model data from multiple sources with Power Query.' },
      { module: 'Module 6', title: 'Macros, VBA & Automation', lessons: 8, duration: '3 weeks', description: 'Record and write macros to automate repetitive tasks and workflows.' },
    ],
    reviews: [
      { name: 'Emeka J.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop', rating: 5, comment: 'Chris is the best Excel teacher on the internet. My productivity at work has tripled.', date: 'Mar 2026' },
      { name: 'Lisa P.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop', rating: 5, comment: 'Went from knowing nothing to building full dashboards for my company. Incredible course.', date: 'Feb 2026' },
      { name: 'Ahmed R.', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=60&h=60&fit=crop', rating: 5, comment: 'The Power Query section alone saved me 5 hours of work every week. Worth every cent.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'project-management',
    title: 'Project Management',
    provider: 'LearnFlow',
    instructor: 'James Okafor (PMP)',
    instructorTitle: 'Project Management Professional, 18+ years experience',
    instructorAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/9LSnINglkQA',
    rating: 4.7,
    reviewCount: 33000,
    students: 245000,
    duration: '4 months',
    hoursPerWeek: '8 hrs/week',
    level: 'Beginner',
    price: '$39.99',
    originalPrice: '$149.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Master project management methodologies, tools, and leadership skills to pass the PMP exam and lead successful projects.',
    description: 'James Okafor has managed over $500M in projects across industries. This course prepares you for the PMP certification while giving you the practical skills to lead real projects from initiation to close.',
    benefits: [
      'Prepare for the PMP certification exam',
      'Learn Agile, Scrum, Waterfall, and hybrid approaches',
      'Master project planning, risk, and stakeholder management',
      'Use industry tools like MS Project and Jira',
      'Learn from a PM with $500M+ in project experience',
      'Career support for PM and program manager roles',
    ],
    skills: ['Project Planning', 'Agile & Scrum', 'Risk Management', 'Stakeholder Management', 'MS Project', 'Jira', 'Budgeting', 'Change Management'],
    curriculum: [
      { module: 'Module 1', title: 'Project Management Foundations', lessons: 10, duration: '2 weeks', description: 'Understand the project lifecycle, PMBOK framework, and PM roles.' },
      { module: 'Module 2', title: 'Project Planning & Scheduling', lessons: 14, duration: '3 weeks', description: 'Create WBS, Gantt charts, and project schedules using MS Project.' },
      { module: 'Module 3', title: 'Agile & Scrum Methodology', lessons: 16, duration: '3 weeks', description: 'Run sprints, manage backlogs, and lead Agile teams with Jira.' },
      { module: 'Module 4', title: 'Risk & Quality Management', lessons: 12, duration: '3 weeks', description: 'Identify, assess, and mitigate project risks and quality issues.' },
      { module: 'Module 5', title: 'Stakeholder & Communication Management', lessons: 10, duration: '2 weeks', description: 'Manage stakeholder expectations and communicate project status effectively.' },
      { module: 'Module 6', title: 'PMP Exam Prep & Capstone', lessons: 10, duration: '5 weeks', description: 'Review all PMP exam domains and complete a full project simulation.' },
    ],
    reviews: [
      { name: 'Funmi A.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Passed my PMP on the first attempt! James explains everything with real project examples.', date: 'Mar 2026' },
      { name: 'Derek W.', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=60&h=60&fit=crop', rating: 5, comment: 'The Agile and Scrum section is the best I have seen. Immediately applied it at work.', date: 'Feb 2026' },
      { name: 'Yetunde B.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Very comprehensive. The risk management module is particularly well done.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'python-skill',
    title: 'Python',
    provider: 'University of Michigan',
    instructor: 'Dr. Charles Severance (U of Michigan)',
    instructorTitle: 'Clinical Professor, University of Michigan',
    instructorAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/8DvywoWv6fI',
    rating: 4.9,
    reviewCount: 245000,
    students: 5800000,
    duration: '8 months',
    hoursPerWeek: '4 hrs/week',
    level: 'Beginner',
    price: '$29.99',
    originalPrice: '$99.99',
    language: 'English',
    lastUpdated: 'February 2026',
    shortDescription: 'Learn Python programming from scratch with Dr. Chuck — the world\'s most popular Python instructor from the University of Michigan.',
    description: 'Dr. Charles Severance (Dr. Chuck) has taught Python to over 5.8 million learners worldwide. This course takes you from your first line of code to building real applications with data, APIs, and databases.',
    benefits: [
      'No prior programming experience needed',
      'Learn from the world\'s most popular Python instructor',
      'Build real applications from day one',
      'Earn a University of Michigan certificate',
      'Access to 5.8 million learner community',
      'Flexible self-paced learning schedule',
    ],
    skills: ['Python Basics', 'Data Structures', 'Functions & OOP', 'File I/O', 'Web Scraping', 'APIs', 'SQL with Python', 'Data Visualization'],
    curriculum: [
      { module: 'Module 1', title: 'Python Basics', lessons: 14, duration: '5 weeks', description: 'Variables, expressions, conditionals, loops, and functions.' },
      { module: 'Module 2', title: 'Data Structures', lessons: 12, duration: '4 weeks', description: 'Lists, dictionaries, tuples, and sets in Python.' },
      { module: 'Module 3', title: 'Object-Oriented Programming', lessons: 12, duration: '4 weeks', description: 'Classes, objects, inheritance, and encapsulation.' },
      { module: 'Module 4', title: 'Files, Exceptions & Modules', lessons: 10, duration: '3 weeks', description: 'Read and write files, handle errors, and use Python modules.' },
      { module: 'Module 5', title: 'Web Data & APIs', lessons: 12, duration: '4 weeks', description: 'Scrape web data, consume REST APIs, and parse JSON and XML.' },
      { module: 'Module 6', title: 'Databases & Capstone Project', lessons: 10, duration: '12 weeks', description: 'Use SQLite with Python and build a complete data application.' },
    ],
    reviews: [
      { name: 'Ngozi E.', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop', rating: 5, comment: 'Dr. Chuck is the best programming teacher I have ever had. Made Python feel easy and fun.', date: 'Mar 2026' },
      { name: 'Liam W.', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=60&h=60&fit=crop', rating: 5, comment: 'Started with zero coding knowledge. Now I write Python scripts for my job every day.', date: 'Feb 2026' },
      { name: 'Yuki T.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop', rating: 4, comment: 'Excellent pacing for beginners. The database section is particularly well done.', date: 'Jan 2026' },
    ],
  },

  {
    id: 'sql-skill',
    title: 'SQL',
    provider: 'LearnFlow',
    instructor: 'Mia Chen (Ex-Netflix)',
    instructorTitle: 'Senior Data Engineer, Ex-Netflix',
    instructorAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop',
    category: 'Skills',
    thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=450&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/HXV3zeQKqGY',
    rating: 4.8,
    reviewCount: 61000,
    students: 430000,
    duration: '2 months',
    hoursPerWeek: '6 hrs/week',
    level: 'Beginner',
    price: '$24.99',
    originalPrice: '$89.99',
    language: 'English',
    lastUpdated: 'March 2026',
    shortDescription: 'Master SQL from basics to advanced queries. Learn the database skills used daily by data teams at Netflix and top tech companies.',
    description: 'Mia Chen spent years writing SQL at Netflix scale. This course teaches you everything from your first SELECT statement to complex window functions, CTEs, and query optimization — the skills that get you hired.',
    benefits: [
      'Learn SQL used at Netflix-scale data teams',
      'Go from zero to advanced SQL in 2 months',
      'Master joins, subqueries, and window functions',
      'Work with real-world datasets throughout',
      'Earn a job-ready SQL certificate',
      'Skills applicable to any database platform',
    ],
    skills: ['SELECT & Filtering', 'JOINs', 'Aggregations', 'Subqueries', 'CTEs', 'Window Functions', 'Query Optimization', 'Database Design'],
    curriculum: [
      { module: 'Module 1', title: 'SQL Fundamentals', lessons: 12, duration: '1 week', description: 'Write your first queries: SELECT, WHERE, ORDER BY, and LIMIT.' },
      { module: 'Module 2', title: 'Filtering, Aggregation & Grouping', lessons: 14, duration: '2 weeks', description: 'Use GROUP BY, HAVING, COUNT, SUM, AVG, and aggregate functions.' },
      { module: 'Module 3', title: 'Joins & Relationships', lessons: 16, duration: '2 weeks', description: 'Master INNER, LEFT, RIGHT, and FULL JOINs across multiple tables.' },
      { module: 'Module 4', title: 'Subqueries & CTEs', lessons: 12, duration: '2 weeks', description: 'Write nested queries and use Common Table Expressions for complex logic.' },
      { module: 'Module 5', title: 'Window Functions & Advanced SQL', lessons: 14, duration: '2 weeks', description: 'Use ROW_NUMBER, RANK, LAG, LEAD, and PARTITION BY for analytics.' },
      { module: 'Module 6', title: 'Query Optimization & Capstone', lessons: 8, duration: '3 weeks', description: 'Optimize slow queries, understand indexes, and complete a real analytics project.' },
    ],
    reviews: [
      { name: 'Kofi A.', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=60&h=60&fit=crop', rating: 5, comment: 'Mia teaches SQL the way it is actually used at top companies. The window functions section is gold.', date: 'Mar 2026' },
      { name: 'Priya R.', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop', rating: 5, comment: 'Went from knowing nothing to writing complex analytical queries in 6 weeks. Incredible.', date: 'Feb 2026' },
      { name: 'Sam T.', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=60&h=60&fit=crop', rating: 5, comment: 'The best SQL course I have taken. Real datasets, real problems, real skills.', date: 'Jan 2026' },
    ],
  },

];

// Map catalog items to course IDs for the list grids
export const COURSE_TITLE_MAP = {};
CATALOG_COURSES.forEach(c => { COURSE_TITLE_MAP[c.title] = c.id; });
